name: Required Reviews
on:
  pull_request: {}
jobs:
  required-reviews:
    name: Required Reviews
    runs-on: ubuntu-latest
    steps:
      - uses: theoremlp/required-reviews@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
